export const API_KEY = '82o5V3l2MeiKHQOSRu66wWTDBCiyYiwC'
export const BASE_URL = 'https://api.nytimes.com/svc/topstories/v2'
export const DEFAULT_CATEGORY = 'world'
export const DEFAULT_LOCATION = ''
export const NEWS_LIST_PERSIST_KEY = '@newslist'
export const CATEGORY_PERSIST_KEY = '@category'
export const LOCATION_PERSIST_KEY = '@location'